# application url
url1=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url2=http://localhost/orangehrm/web/index.php/auth/login
url=https://tutorialsninja.com/demo/
# browser configuration
browser=chrome
# credentials
username=orangehrm_chaker
password=2U8@C7VGxvtx@r
email=chakerbensaid1@gmail.com
# implicit wait time (in seconds)
timeout=15
# explicit wait time (in seconds)
explicit=25
# Execution Target (true = run on Selenium Grid, false = run locally)
isGrid=false
# Selenium Grid Hub URL
gridUrl=http://localhost:4444/wd/hub
# Execution in Headless mode
headless=false
# LambdaTest User credentials
LT_USERNAME=chakerbensaid1mockinbox
LT_ACCESS_KEY=LT_95A1XnCh8ufgFfPUKZopTAeKO2zVnbTmMoeGuTU33qLEIzW
# Execution Target (true = run on LambdaTest Cloud, false = run locally)
LambdaTest=true
# LambdaTest hub URL
hub=@hub.lambdatest.com/wd/hub
