# application url
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
# browser configuration
browser=chrome
# credentials
username=Admin
password=admin123
# implicit wait time (in seconds)
timeout=15
# explicit wait time (in seconds)
explicit=25
